name: run .py script please

on:
  schedule:
    - cron:  '30 0,4,8,12,16,20 * * *'
  workflow_dispatch:
  

jobs:
  update-wiseoldman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pwsh script.py
