name: run .py script please

on:
  schedule:
    - cron:  "* * * * *"
  workflow_dispatch:
  

jobs:
  saveTimeToTxtFile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pwsh script.py
